resources:
  'entity:node':
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
    POST:
      supported_formats:
        - json
      supported_auth:
        - cookie
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - cookie
    PATCH:
      supported_formats:
        - json
      supported_auth:
        - cookie
